DROP TABLE Z_USERS CASCADE CONSTRAINTS;
DROP TABLE Z_ADDRESSES CASCADE CONSTRAINTS;
DROP TABLE Z_COUNTRIES CASCADE CONSTRAINTS;
DROP TABLE Z_CITIES CASCADE CONSTRAINTS;
DROP TABLE Z_LAPTOPS CASCADE CONSTRAINTS;
DROP TABLE Z_LAPTOP_BRANDS CASCADE CONSTRAINTS;
DROP TABLE Z_CPU_BRANDS CASCADE CONSTRAINTS;
DROP TABLE Z_ORDER_LINES CASCADE CONSTRAINTS;
DROP TABLE Z_LAPTOP_ORDERS CASCADE CONSTRAINTS;
DROP TABLE Z_SHIPPING_METHODS CASCADE CONSTRAINTS;

prompt
prompt Creating table Z_COUNTRIES
prompt ======================
prompt

CREATE TABLE Z_COUNTRIES
(
    COUNTRY_ID NUMBER(10) CONSTRAINT PK_COUNTRY_ID PRIMARY KEY,
    NAME VARCHAR2(50) CONSTRAINT NN_COUNTRY_NAME NOT NULL
                      CONSTRAINT UNQ_COUNTRY_NAME UNIQUE
);
    
prompt
prompt Creating table Z_CITIES
prompt ======================
prompt

CREATE TABLE Z_CITIES
(
    CITY_ID NUMBER(10) CONSTRAINT PK_CITY_ID PRIMARY KEY,
    NAME VARCHAR2(50) CONSTRAINT NN_CITY_NAME NOT NULL
                      CONSTRAINT UNQ_CITY_NAME UNIQUE
);
    
prompt
prompt Creating table Z_ADDRESSES
prompt ======================
prompt

CREATE TABLE Z_ADDRESSES
(
    ADDRESS_ID NUMBER(10) CONSTRAINT PK_ADDRESS_ID PRIMARY KEY,
    COUNTRY_ID NUMBER(10) CONSTRAINT NN_COUNTRY_ID NOT NULL,
    CITY_ID NUMBER(10) CONSTRAINT NN_CITY_ID NOT NULL,
    STREET_NAME VARCHAR2(100),
    STREET_NUMBER NUMBER(5),
    POSTAL_CODE NUMBER(10)
);

ALTER TABLE Z_ADDRESSES
    ADD CONSTRAINT FK_COUNTRY_ID FOREIGN KEY (COUNTRY_ID)
    REFERENCES Z_COUNTRIES (COUNTRY_ID);
ALTER TABLE Z_ADDRESSES
    ADD CONSTRAINT FK_CITY_ID FOREIGN KEY (CITY_ID)
    REFERENCES Z_CITIES (CITY_ID);

prompt
prompt Creating table Z_USERS
prompt ======================
prompt

CREATE TABLE Z_USERS
(
    USER_ID NUMBER(10) CONSTRAINT PK_USER_ID PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) CONSTRAINT NN_FIRST_NAME NOT NULL,
    LAST_NAME VARCHAR(50) CONSTRAINT NN_LAST_NAME NOT NULL,
    EMAIL VARCHAR2(50) CONSTRAINT NN_EMAIL NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    ADDRESS_ID NUMBER(10)
);

ALTER TABLE Z_USERS
    ADD CONSTRAINT FK_ADDRESS_ID FOREIGN KEY (ADDRESS_ID)
    REFERENCES Z_ADDRESSES (ADDRESS_ID);
    
prompt
prompt Creating table Z_SHIPPING_METHODS
prompt ======================
prompt

CREATE TABLE Z_SHIPPING_METHODS
(
    SHIPPING_METHOD_ID NUMBER(1) CONSTRAINT PK_SHIPPING_METHOD_ID PRIMARY KEY,
    NAME VARCHAR2(30) CONSTRAINT NN_SHIPPING_METHOD_NAME NOT NULL
                      CONSTRAINT UNQ_SHIPPING_METHOD_NAME UNIQUE,
    PRICE NUMBER(4,2) CONSTRAINT NN_PRICE NOT NULL
);

ALTER TABLE Z_SHIPPING_METHODS
    ADD CONSTRAINT CHK_SHIPPING_PRICE CHECK (PRICE >= 0);

prompt
prompt Creating table Z_SHIPPING_METHODS
prompt ======================
prompt

CREATE TABLE Z_LAPTOP_ORDERS
(
    LAPTOP_ORDER_ID NUMBER(10) CONSTRAINT PK_LAPTOP_ORDER_ID PRIMARY KEY,
    USER_ID NUMBER(10) CONSTRAINT NN_USER_ID NOT NULL,
    ORDER_DATE DATE,
    SHIPPING_METHOD_ID NUMBER(1) CONSTRAINT NN_SHIPPING_METHOD_ID NOT NULL,
    STATUS VARCHAR2(100)
);
    
ALTER TABLE Z_LAPTOP_ORDERS
    ADD CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID)
    REFERENCES Z_USERS (USER_ID);
ALTER TABLE Z_LAPTOP_ORDERS
    ADD CONSTRAINT FK_SHIPPING_METHOD_ID FOREIGN KEY (SHIPPING_METHOD_ID)
    REFERENCES Z_SHIPPING_METHODS (SHIPPING_METHOD_ID);

prompt
prompt Creating table Z_LAPTOP_BRANDS
prompt ======================
prompt

CREATE TABLE Z_LAPTOP_BRANDS
(
    LAPTOP_BRAND_ID NUMBER(2) CONSTRAINT PK_LAPTOP_BRAND_ID PRIMARY KEY,
    NAME VARCHAR2(30) CONSTRAINT NN_LAPTOP_BRAND_NAME NOT NULL
                      CONSTRAINT UNQ_LAPTOP_BRAND_NAME UNIQUE
);

prompt
prompt Creating table Z_CPU_BRANDS
prompt ======================
prompt

CREATE TABLE Z_CPU_BRANDS 
(
    CPU_BRAND_ID NUMBER(2) CONSTRAINT PK_CPU_BRAND_ID PRIMARY KEY,
    NAME VARCHAR2(20) CONSTRAINT NN_CPU_BRAND_NAME NOT NULL
                      CONSTRAINT UNQ_CPU_BRAND_NAME UNIQUE
);

prompt
prompt Creating table Z_LAPTOPS
prompt ======================
prompt

CREATE TABLE Z_LAPTOPS
(
    LAPTOP_ID NUMBER(10) CONSTRAINT PK_LAPTOP_ID PRIMARY KEY,
    LAPTOP_BRAND_ID NUMBER(2) CONSTRAINT NN_LAPTOP_BRAND_ID NOT NULL,
    LAPTOP_MODEL VARCHAR2(30),
    CPU_BRAND_ID NUMBER(2) CONSTRAINT NN_CPU_BRAND_ID NOT NULL,
    CPU_TYPE VARCHAR2(20),
    DISPLAY_SIZE NUMBER(3,1),
    RAM_MEMORY_SIZE NUMBER(3),
    SSD_MEMORY_SIZE NUMBER(4),
    GRAPHICS_CARD VARCHAR2(20),
    OPERATING_SYSTEM VARCHAR2(20),
    COLOR VARCHAR2(20),
    PRICE NUMBER(10, 2)
);

ALTER TABLE Z_LAPTOPS
    ADD CONSTRAINT FK_LAPTOP_BRAND_ID FOREIGN KEY (LAPTOP_BRAND_ID)
    REFERENCES Z_LAPTOP_BRANDS (LAPTOP_BRAND_ID);
ALTER TABLE Z_LAPTOPS
    ADD CONSTRAINT FK_CPU_BRAND_ID FOREIGN KEY (CPU_BRAND_ID)
    REFERENCES Z_CPU_BRANDS (CPU_BRAND_ID);

prompt
prompt Creating table Z_ORDER_LINES
prompt ======================
prompt

CREATE TABLE Z_ORDER_LINES
(
    LAPTOP_ORDER_ID NUMBER(10) CONSTRAINT NN_LAPTOP_ORDER_ID NOT NULL,
    LAPTOP_ID NUMBER(10) CONSTRAINT NN_LAPTOP_ID NOT NULL,
    QUANTITY NUMBER(4) CONSTRAINT NN_QUANTITY NOT NULL,
    PRICE NUMBER(10, 2) CONSTRAINT NN_ORDER_LINE_PRICE NOT NULL
);

ALTER TABLE Z_ORDER_LINES
    ADD CONSTRAINT FK_LAPTOP_ORDER_ID FOREIGN KEY (LAPTOP_ORDER_ID)
    REFERENCES Z_LAPTOP_ORDERS (LAPTOP_ORDER_ID);
ALTER TABLE Z_ORDER_LINES
    ADD CONSTRAINT FK_LAPTOP_ID FOREIGN KEY (LAPTOP_ID)
    REFERENCES Z_LAPTOPS (LAPTOP_ID);
ALTER TABLE Z_ORDER_LINES 
    ADD CONSTRAINT CHK_ORDER_LINE_QUANTITY CHECK (QUANTITY >= 1);
ALTER TABLE Z_ORDER_LINES 
    ADD CONSTRAINT CHK_ORDER_LINE_PRICE CHECK (PRICE >= 0);
